from typing import Protocol, Optional, List
from domain.delivery_order import DeliveryOrder


class IDeliveryOrderRepository(Protocol):
    """Контракт репозитория заявок на отгрузку."""

    async def get_by_id(self, order_id: int) -> Optional[DeliveryOrder]: ...
    async def create(self, buyer_id: int, description: str,
                     address_from: str, address_to: str) -> DeliveryOrder: ...
    async def get_open_orders(self) -> List[DeliveryOrder]: ...
    async def get_by_buyer(self, buyer_id: int) -> List[DeliveryOrder]: ...
    async def get_by_loader(self, loader_id: int) -> List[DeliveryOrder]: ...
    async def take(self, order_id: int, loader_id: int) -> bool: ...
    async def start(self, order_id: int, loader_id: int) -> bool: ...
    async def complete(self, order_id: int, loader_id: int,
                       photo: str, comment: str) -> Optional[DeliveryOrder]: ...
    async def cancel(self, order_id: int, buyer_id: int) -> bool: ...
