from typing import Protocol, Optional, List
from domain.product import Product


class IProductRepository(Protocol):
    """Контракт репозитория товаров."""

    async def get_by_id(self, product_id: int) -> Optional[Product]: ...
    async def get_by_seller(self, user_id: int) -> List[Product]: ...
    async def get_by_category(self, category: str,
                               category_two: Optional[str] = None,
                               category_three: Optional[str] = None) -> List[Product]: ...
    async def create(self, user_id: int, name: str, description: str,
                     category: str, category_two: str, category_three: str,
                     price: float, photo: str) -> Product: ...
    async def update(self, product: Product) -> Product: ...
    async def delete(self, product_id: int) -> bool: ...
    async def set_available(self, product_id: int, available: bool) -> None: ...
