from typing import Protocol, Optional, List
from domain.referral import Referral


class IReferralRepository(Protocol):
    """Контракт репозитория реферальной программы."""

    async def get_by_user(self, user_id: int) -> Optional[Referral]: ...
    async def create(self, user_id: int, link: str, referrer_id: int) -> Referral: ...
    async def get_tree(self, user_id: int, max_level: int = 8) -> List[Referral]: ...
    async def get_all_referrers(self, user_id: int) -> List[Referral]: ...
    async def update_balance(self, user_id: int, balance: int) -> None: ...
    async def update_after_buy(self, referrers: List[Referral]) -> None: ...
