from typing import Protocol, Optional, List
from domain.user import User


class IUserRepository(Protocol):
    """Контракт репозитория пользователей.
    
    Handlers зависят ТОЛЬКО от этого интерфейса.
    Конкретная реализация (PostgreSQL, InMemory) подставляется снаружи.
    """

    async def get_by_id(self, user_id: int) -> Optional[User]: ...
    async def create(self, user_id: int, name: str) -> User: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: int) -> bool: ...
    async def exists(self, user_id: int) -> bool: ...
    async def set_city(self, user_id: int, city: str) -> None: ...
    async def set_organization(self, user_id: int, organization: str) -> None: ...
    async def set_offerta(self, user_id: int) -> None: ...
    async def set_phone(self, user_id: int, phone: str) -> None: ...
    async def activate_subscription(self, user_id: int, days: int) -> None: ...
    async def get_all(self) -> List[User]: ...
